// Sample starter data (used when localStorage is empty)
export var SAMPLE_USERS = [
  {
    id: 1,
    username: "alice",
    password: "1234",
    name: "Alice",
    // surname: "Anderson", //§kamen_20251010_175213
    gender: "female",
    // §kamen_20251010_180320
    //roles: ["seeker"]
    roles: ["admin", "seeker"]
  },
  {
    id: 2,
    username: "bob",
    password: "1234",
    name: "Bob",
    // surname: "Brown",//§kamen_20251010_175213
    gender: "male",
    //§kamen_20251010_180320
    roles: ["hider"]
  },
  {
    id: 3,
    username: "charlie",
    password: "1234",
    name: "Charlie",
    gender: "male",
    roles: ["admin", "seeker", "hider"]
  },
  {
    id: 4,
    username: "diana",
    password: "1234",
    name: "Diana",
    gender: "female",
    roles: ["seeker","developer","tester"]
  },
  {
    id: 5,
    username: "evan",
    password: "1234",
    name: "Evan",
    gender: "male",
    roles: ["seeker", "hider"]
  },
  {
    id: 6,
    username: "frank",
    password: "1234",
    name: "Frank",
    gender: "male",
    roles: ["tester"]
  },
  {
    id: 7,
    username: "grace",
    password: "1234",
    name: "Grace",
    gender: "female",
    roles: ["developer"]
  },
];

export var SAMPLE_POINTS = [
  {
    id: 1,
    username: "alice",
    title: "Home",
    lat: 42.6977,
    lng: 23.3219,
    desc: "Alice's home in Sofia",
    status: "pending",
    code: "ALICE123",
    foundBy: null,
  },
  {
    id: 2,
    username: "bob",
    title: "Work",
    lat: 42.1354,
    lng: 24.7453,
    desc: "Bob's office in Plovdiv",
    status: "found",
    code: "BOB456",
    foundBy: "charlie",
  },
  {
    id: 3,
    username: "bob",
    title: "Park Treasure",
    lat: 42.6950,
    lng: 23.3350,
    desc: "Hidden treasure in the park",
    status: "hidden",
    code: "PARK777",
    foundBy: null,
  },
  {
    id: 4,
    username: "evan",
    title: "Mountain Cache",
    lat: 42.7100,
    lng: 23.3500,
    desc: "Cache hidden in the mountains",
    status: "hidden",
    code: "MOUNT999",
    foundBy: null,
  },
  {
    id: 5,
    username: "evan",
    title: "River Spot",
    lat: 42.6850,
    lng: 23.3100,
    desc: "Hidden spot by the river",
    status: "hidden",
    code: "RIVER555",
    foundBy: null,
  },
  {
    id: 6,
    username: "charlie",
    title: "Lake View",
    lat: 42.6800,
    lng: 23.3400,
    desc: "Beautiful spot overlooking the lake",
    status: "hidden",
    code: "LAKE888",
    foundBy: null,
  },
  {
    id: 7,
    username: "bob",
    title: "Forest Trail",
    lat: 42.7050,
    lng: 23.3250,
    desc: "Hidden along the forest trail",
    status: "found",
    code: "FOREST321",
    foundBy: "alice",
  },
  {
    id: 8,
    username: "evan",
    title: "City Center",
    lat: 42.6950,
    lng: 23.3280,
    desc: "Right in the heart of the city",
    status: "pending",
    code: "CITY654",
    foundBy: null,
  },
  {
    id: 9,
    username: "charlie",
    title: "Bridge View",
    lat: 42.6900,
    lng: 23.3150,
    desc: "Under the old bridge",
    status: "hidden",
    code: "BRIDGE987",
    foundBy: null,
  },
  {
    id: 10,
    username: "bob",
    title: "Garden Secret",
    lat: 42.7000,
    lng: 23.3320,
    desc: "Hidden in the botanical garden",
    status: "found",
    code: "GARDEN147",
    foundBy: "evan",
  },
  {
    id: 11,
    username: "alice",
    title: "Historic Square",
    lat: 42.6960,
    lng: 23.3200,
    desc: "Ancient treasure near the old square",
    status: "hidden",
    code: "SQUARE222",
    foundBy: null,
  },
  {
    id: 12,
    username: "charlie",
    title: "University Campus",
    lat: 42.6550,
    lng: 23.3700,
    desc: "Cache hidden on campus grounds",
    status: "pending",
    code: "UNI333",
    foundBy: null,
  },
  {
    id: 13,
    username: "bob",
    title: "Stadium Corner",
    lat: 42.6900,
    lng: 23.3450,
    desc: "Near the old stadium entrance",
    status: "found",
    code: "STADIUM444",
    foundBy: "charlie",
  },
  {
    id: 14,
    username: "evan",
    title: "Metro Station",
    lat: 42.6980,
    lng: 23.3240,
    desc: "Underground cache near metro",
    status: "hidden",
    code: "METRO555",
    foundBy: null,
  },
  {
    id: 15,
    username: "alice",
    title: "Museum Steps",
    lat: 42.6940,
    lng: 23.3310,
    desc: "Hidden at the museum entrance",
    status: "hidden",
    code: "MUSEUM666",
    foundBy: null,
  },
  {
    id: 16,
    username: "charlie",
    title: "Cathedral View",
    lat: 42.6970,
    lng: 23.3230,
    desc: "Cache with cathedral view",
    status: "found",
    code: "CHURCH777",
    foundBy: "bob",
  },
  {
    id: 17,
    username: "bob",
    title: "Market Plaza",
    lat: 42.6920,
    lng: 23.3290,
    desc: "Busy marketplace treasure",
    status: "pending",
    code: "MARKET888",
    foundBy: null,
  },
  {
    id: 18,
    username: "evan",
    title: "Airport Road",
    lat: 42.6890,
    lng: 23.4100,
    desc: "Along the road to airport",
    status: "hidden",
    code: "AIRPORT999",
    foundBy: null,
  },
  {
    id: 19,
    username: "alice",
    title: "Zoo Entrance",
    lat: 42.6500,
    lng: 23.3400,
    desc: "Near the zoo main gate",
    status: "hidden",
    code: "ZOO101",
    foundBy: null,
  },
  {
    id: 20,
    username: "charlie",
    title: "Tower Monument",
    lat: 42.7020,
    lng: 23.3180,
    desc: "At the base of the monument",
    status: "found",
    code: "TOWER202",
    foundBy: "alice",
  },
];
